name = "Convertsible"
uuid = "5e5609d0-9833-45e2-af04-2331796b8885"
authors = ["Matthieu Tisserand <matthieu.tisserand@polytechnique.org> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
